definitions:
  model.Subject:
    properties:
      subject_id:
        type: string
      subject_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /subject/:
    get:
      consumes:
      - application/json
      description: Get all Subject
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subject'
            type: array
      tags:
      - Subject
    post:
      consumes:
      - application/json
      description: Create a new subject
      parameters:
      - description: Subject object that needs to be added
        in: body
        name: subject
        required: true
        schema:
          $ref: '#/definitions/model.Subject'
      produces:
      - application/json
      responses:
        "200":
          description: Subject created successfully
          schema:
            type: string
      tags:
      - Subject
  /subject/{document_id}:
    delete:
      consumes:
      - application/json
      description: Delete subject by ID
      parameters:
      - description: document_id of the subject to be deleted
        in: path
        name: document_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Subject deleted successfully
          schema:
            type: string
      tags:
      - Subject
    get:
      consumes:
      - application/json
      description: Get subject by ID
      parameters:
      - description: document_id of the subject to be deleted
        in: path
        name: document_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subject'
      tags:
      - Subject
  /subject/{subject_id}:
    put:
      consumes:
      - application/json
      description: Update subject by ID
      parameters:
      - description: document_id of the subject to be deleted
        in: path
        name: document_id
        required: true
        type: string
      - description: Subject object that needs to be updated
        in: body
        name: subject
        required: true
        schema:
          $ref: '#/definitions/model.Subject'
      produces:
      - application/json
      responses:
        "200":
          description: Subject updated successfully
          schema:
            type: string
      tags:
      - Subject
swagger: "2.0"
