info:
  contact: {}
paths:
  /helloworld:
    get:
      consumes:
      - application/json
      description: do hello world ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello world
      tags:
      - HelloWorld
swagger: "2.0"
