info:
  contact: {}
paths:
  /student/list:
    get:
      consumes:
      - application/json
      description: Get all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      tags:
      - Student
  /subject/list:
    get:
      consumes:
      - application/json
      description: Get all Subject
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      tags:
      - Subject
swagger: "2.0"
