info:
  contact: {}
paths:
  /helloworld:
    get:
      consumes:
      - application/json
      description: do hello world ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: hello world
      tags:
      - HelloWorld
  /student/list:
    get:
      consumes:
      - application/json
      description: Get all students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      tags:
      - Student
swagger: "2.0"
